touchpad:
  gestures:
    - type: swipe
      direction: right
      speed: slow
      fingers: 3

      actions:
        - input:
          - mouse: [ forward ]

    - type: swipe
      direction: left
      speed: slow
      fingers: 3

      actions:
        - input:
          - mouse: [ back ]
