#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    template = 'root <#ffffff>in</> '
    background = 'transparent'
    foreground = '#E06C75'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = '{{ .Path }} '
    background = 'transparent'
    foreground = '#55B9C4'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    template = '<#ffffff>on</> {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    background = 'transparent'
    foreground = '#C678DD'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      fetch_status = true

  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    template = '<#ffffff>via</>  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '
    background = 'transparent'
    foreground = '#98C379'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    template = 'x '
    background = 'transparent'
    foreground = '#C94A16'
    Text = ''
    Duration = 0
    NameLength = 0

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '➜ '
    background = 'transparent'
    foreground = '#63F08C'
    Text = ''
    Duration = 0
    NameLength = 0